steps:
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
  # Build will run inside the Docker builder stage so build-time NEXT_PUBLIC_*
  # values must be passed as build-args to docker. Use Cloud Build substitutions
  # (e.g. _NEXT_PUBLIC_APP_URL) when triggering the build or configure your
  # Cloud Build trigger to set these variables from Secret Manager.
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          docker build -t asia-south1-docker.pkg.dev/project-949bf9a3-f980-4d1a-82b/frontend/frontend:v1 \
            --build-arg NEXT_PUBLIC_APP_URL="$NEXT_PUBLIC_APP_URL" \
            --build-arg NEXT_PUBLIC_API_BASE_URL="$NEXT_PUBLIC_API_BASE_URL" \
            --build-arg NEXT_PUBLIC_PING_ISSUER="$NEXT_PUBLIC_PING_ISSUER" \
            --build-arg NEXT_PUBLIC_PING_CLIENT_ID="$NEXT_PUBLIC_PING_CLIENT_ID" \
            --build-arg NEXT_PUBLIC_PING_REDIRECT_URI="$NEXT_PUBLIC_PING_REDIRECT_URI" \
            --build-arg NEXT_PUBLIC_PING_LOGOUT_URI="$NEXT_PUBLIC_PING_LOGOUT_URI" \
            --build-arg NEXT_PUBLIC_PING_SCOPE="$NEXT_PUBLIC_PING_SCOPE" \
            --build-arg SKIP_ENV_VALIDATION="$SKIP_ENV_VALIDATION" \
            .
  # Example defaults (override at trigger time). Remove or replace with safe defaults
  # or configure your Cloud Build trigger to inject secrets instead of hardcoding.
    substitutions:
      _NEXT_PUBLIC_APP_URL: ""
      _NEXT_PUBLIC_API_BASE_URL: ""
      _NEXT_PUBLIC_PING_ISSUER: ""
      _NEXT_PUBLIC_PING_CLIENT_ID: ""
      _NEXT_PUBLIC_PING_REDIRECT_URI: ""
      _NEXT_PUBLIC_PING_LOGOUT_URI: ""
      _NEXT_PUBLIC_PING_SCOPE: ""
      _SKIP_ENV_VALIDATION: "true"

availableSecrets:
  secretManager:
    # Replace projects/PROJECT_ID/secrets/SECRET_NAME/versions/latest with your
    # project's actual secret resource paths. The 'env' value becomes the
    # environment variable available in build steps (used above).
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_APP_URL/versions/latest"
      env: "NEXT_PUBLIC_APP_URL"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_API_BASE_URL/versions/latest"
      env: "NEXT_PUBLIC_API_BASE_URL"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_PING_ISSUER/versions/latest"
      env: "NEXT_PUBLIC_PING_ISSUER"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_PING_CLIENT_ID/versions/latest"
      env: "NEXT_PUBLIC_PING_CLIENT_ID"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_PING_REDIRECT_URI/versions/latest"
      env: "NEXT_PUBLIC_PING_REDIRECT_URI"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_PING_LOGOUT_URI/versions/latest"
      env: "NEXT_PUBLIC_PING_LOGOUT_URI"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/NEXT_PUBLIC_PING_SCOPE/versions/latest"
      env: "NEXT_PUBLIC_PING_SCOPE"
      - versionName: "projects/project-949bf9a3-f980-4d1a-82b/secrets/SKIP_ENV_VALIDATION/versions/latest"
      env: "SKIP_ENV_VALIDATION"