steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/ust-gcp-costco-replatform-poc/signs-spa-repo/frontend:$SHORT_SHA'
      - '.'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/ust-gcp-costco-replatform-poc/signs-spa-repo/frontend:$SHORT_SHA'

  # Step 3: Deploy to GKE Cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/my-deployment'
      - 'my-container=us-central1-docker.pkg.dev/ust-gcp-costco-replatform-poc/signs-spa-repo/frontend:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster-name'

images:
  - 'us-central1-docker.pkg.dev/ust-gcp-costco-replatform-poc/signs-spa-repo/frontend:$SHORT_SHA'