steps:
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-949bf9a3-f980-4d1a-82b/frontend/frontend:v1', '.']

images:
  - 'us-central1-docker.pkg.dev/project-949bf9a3-f980-4d1a-82b/frontend/frontend:v1'

options:
  logging: CLOUD_LOGGING_ONLY