apiVersion: v1
kind: Secret
metadata:
  name: #{SERVICE_IMAGENAME}-#{SERVICE_TYPE}-tls-secret
  namespace: #{GKE_NAMESPACE}
  labels:
    certificate-name: #{GKE_SECRET_CERT_NAME}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
