apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: #{SERVICE_IMAGENAME}-#{SERVICE_TYPE}-pdb-nextgen
  namespace: #{GKE_NAMESPACE}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: #{SERVICE_IMAGENAME}-#{SERVICE_TYPE}
