apiVersion: v1
kind: Secret
metadata:
  name: #{SERVICE_IMAGENAME}-#{SERVICE_TYPE}-db-secret
  namespace: #{GKE_NAMESPACE}
type: Opaque
stringData:
  # These values should be replaced with actual credentials
  # Consider using Google Secret Manager instead for production
  DB_PASSWORD: |-
    #{DB_PASSWORD}
  DB_USERNAME: |-
    #{DB_USERNAME}
