apiVersion: v1
kind: ServiceAccount
metadata:
  name: #{KSA_SERVICEACCOUNT}
  namespace: #{GKE_NAMESPACE}
  labels:
    component: serviceaccount
  annotations:
    iam.gke.io/gcp-service-account: #{GKE_RUN_SERVICE_ACCOUNT}
    description: "Workload Identity for Costco Vendor Management Service"
automountServiceAccountToken: false
